Failure # 1 (occurred at 2023-02-01_18-07-44)
[36mray::QTrainer.train()[39m (pid=31052, ip=127.0.0.1, repr=<Trainer.q_trainer.QTrainer object at 0x000001D0F9AF6E50>)
  File "python\ray\_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\tune\trainable\trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\tune\trainable\trainable.py", line 364, in train
    result = self.step()
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Code\EmmanuelProject\Trainer\q_trainer.py", line 22, in step
    state = getState(data, 0, window_size + 1)
NameError: name 'getState' is not defined
