[ERROR 2023-02-01 18:00:05,858] worker.py: 763  Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::QTrainer.__init__()[39m (pid=18288, ip=127.0.0.1, repr=<Trainer.q_trainer.QTrainer object at 0x000001816E8A2790>)
  File "python\ray\_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\tune\trainable\trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "D:\Code\EmmanuelProject\venv39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Code\EmmanuelProject\Trainer\q_trainer.py", line 9, in setup
    self.agent = Agent(window_size)
NameError: name 'Agent' is not defined
